plugins { id 'com.android.application' }

android {
    namespace 'com.pitak.obdscan'
    compileSdk 34
    defaultConfig {
        applicationId 'com.pitak.obdscan'
        minSdk 23
        targetSdk 33
        versionCode((System.getenv('GITHUB_RUN_NUMBER') ?: '1') as int)
        versionName '0.5.' + (System.getenv('GITHUB_RUN_NUMBER') ?: '0')
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint { abortOnError false; checkReleaseBuilds false }
}
